"""Streams-vs-quality capacity curve: the only performance metric that matters.

The PM controller degrades gracefully, so "capacity" is not a number — it is a
CURVE. At N concurrent streams the controller settles on some operating point
(detector resolution tier mix + frame-skip fraction) and that operating point
implies a tracking quality. This tool joins the two halves:

  1. QUALITY TABLE (offline, from track.py --eval): quality per content group
     for each (resolution cap x analytics rate) operating point.
     Generated by the eval grid; see /mldata/config/track/quality_table.yaml.
  2. OPERATING POINT (online, from rt_benchmark --csv): at each stream count,
     the achieved PM tier distribution and skip fraction.

Output: quality vs number of streams, per content group, for one or more
policies — so two policies can be compared as curves rather than as anecdotes.

Usage:
    python -m src.capacity_curve --csv POLICY=path/to/rt.csv [POLICY2=...] \
        [--table /mldata/config/track/quality_table.yaml] [--group ALL]

The rt_benchmark CSV header is stale (fewer names than the rows have values);
the true column order is asserted below and taken from rt_benchmark.c.
"""
import argparse
import sys

import yaml

# Fixed leading columns, from src/apps/rt_benchmark.c sweep_step(). The pm
# columns between mean_roi and motion_percent are DYNAMIC (one per pm_table
# row — the table grew from 4 to 6); parse_csv counts them per file.
FIXED_COLS = ["streams", "fps_total", "fps_min", "fps_max", "skipped_percent",
              "force_skip_rate", "force_skip_cv", "mean_batch", "lat50",
              "lat90", "iq50", "iq99", "mean_roi"]

# The CURRENT pm_table (ubon_cstuff include/pm_controller.h): each row is a
# (res_cap, rate) operating point; cap 0 = engine default 640. MUST match the
# header — the effective resolution/rate of a measured PM mix depends on it.
PM_TABLE = [(640, 1.00), (512, 1.00), (512, 0.50),
            (416, 0.50), (416, 0.33), (320, 0.33)]
# Older 4-column CSVs came from the resolution-only ladder:
PM_TABLE_LEGACY = [(640, 1.00), (512, 1.00), (416, 1.00), (320, 1.00)]


def parse_csv(path):
    rows = []
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("streams,"):
            continue
        parts = line.split(",")
        if len(parts) < len(FIXED_COLS) + 4 or not parts[0].isdigit():
            continue
        row = {k: float(v) for k, v in zip(FIXED_COLS, parts)}
        # Everything between the fixed columns and the trailing
        # motion_percent is the pm distribution (4 = legacy ladder, 6 =
        # current (res,rate) table; motion_percent absent on the oldest CSVs).
        rest = [float(v) for v in parts[len(FIXED_COLS):]]
        if len(rest) in (5, 7):
            row["motion_percent"], pms = rest[-1], rest[:-1]
        else:
            row["motion_percent"], pms = 0.0, rest
        row["pm"] = pms
        row["pm_table"] = PM_TABLE if len(pms) >= 6 else PM_TABLE_LEGACY
        rows.append(row)
    return rows


def quality_at(table, group, res, rate):
    """Bilinear-ish lookup: interpolate on rate within each bracketing
    resolution, then interpolate between resolutions. Both axes are sparse and
    monotone, so linear interpolation is adequate and honest."""
    def q_res(r_key):
        row = table[r_key]
        rates = sorted((float(k) for k in row), reverse=True)
        vals = {float(k): row[k].get(group, row[k].get("ALL")) for k in row}
        if rate >= rates[0]:
            return vals[rates[0]]
        if rate <= rates[-1]:
            return vals[rates[-1]]
        for a, b in zip(rates, rates[1:]):
            if b <= rate <= a:
                f = (rate - b) / (a - b)
                return vals[b] + f * (vals[a] - vals[b])
        return vals[rates[-1]]

    res_keys = sorted((int(k) for k in table), reverse=True)
    if res >= res_keys[0]:
        return q_res(str(res_keys[0]))
    if res <= res_keys[-1]:
        return q_res(str(res_keys[-1]))
    for a, b in zip(res_keys, res_keys[1:]):
        if b <= res <= a:
            f = (res - b) / (a - b)
            return q_res(str(b)) + f * (q_res(str(a)) - q_res(str(b)))
    return q_res(str(res_keys[-1]))


def curve(rows, table, table_carry, group):
    out = []
    for r in rows:
        # effective resolution = PM-fraction-weighted mean of the row caps
        pmt = r["pm_table"]
        wsum = sum(r["pm"])
        res = (sum(f * pmt[i][0] for i, f in enumerate(r["pm"])) / wsum) if wsum > 0 else 640
        # effective analytics rate = what survives the controller's frame
        # skip. force_skip_rate is the MEASURED realized skip, which already
        # includes the table rows' own rate dithering — do not multiply the
        # row rates in again.
        rate = max(0.0, 1.0 - r["force_skip_rate"])
        # What fraction of the shed frames kept an optical-flow carry instead of
        # vanishing? With performance.skip_mode: motion nothing is dropped at the
        # decoder, so motion frames per delivered frame ~= shed frames per source
        # frame and this lands at ~1; in drop mode there are no motion frames and
        # it is 0. Anything between blends the two measured tables.
        w = (r["motion_percent"] / r["force_skip_rate"]
             if r["force_skip_rate"] > 1e-6 else 0.0)
        w = min(1.0, max(0.0, w))
        q = quality_at(table, group, res, rate)
        if w > 0 and table_carry:
            q = (1.0 - w) * q + w * quality_at(table_carry, group, res, rate)
        out.append({"streams": int(r["streams"]), "res": res, "rate": rate,
                    "quality": q, "carry": w, "fps_min": r["fps_min"],
                    "lat90": r["lat90"], "batch": r["mean_batch"]})
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="append", required=True,
                    metavar="NAME=PATH", help="policy name = rt_benchmark csv")
    ap.add_argument("--table", default="/mldata/config/track/quality_table.yaml")
    ap.add_argument("--group", default="ALL",
                    help="content group: ALL, static, moving, movie, ...")
    a = ap.parse_args()

    doc = yaml.safe_load(open(a.table))
    table = doc["table"]
    table_carry = doc.get("table_motion_carry")
    groups = sorted({g for row in table.values() for cell in row.values() for g in cell})
    if a.group not in groups:
        sys.exit(f"group {a.group!r} not in table; available: {groups}")

    curves = {}
    for spec in a.csv:
        name, _, path = spec.partition("=")
        curves[name] = curve(parse_csv(path), table, table_carry, a.group)

    print(f"content group: {a.group}   (quality = track.py fitness_multi)")
    hdr = f"{'streams':>8s}"
    for n in curves:
        hdr += f" | {n:>28s}"
    print(hdr)
    print(f"{'':>8s}" + "".join(" | {:>28s}".format("eff_res  rate  cry  quality")
                                   for _ in curves))
    all_n = sorted({p["streams"] for c in curves.values() for p in c})
    for n in all_n:
        line = f"{n:8d}"
        for name, c in curves.items():
            p = next((x for x in c if x["streams"] == n), None)
            line += (f" | {p['res']:7.0f} {p['rate']:5.2f} {p['carry']:4.2f}"
                     f" {p['quality']:8.4f}"
                     if p else f" | {'-':>28s}")
        print(line)

    if len(curves) == 2:
        (n1, c1), (n2, c2) = list(curves.items())
        print(f"\ndelta ({n2} - {n1}) by stream count:")
        for n in all_n:
            p1 = next((x for x in c1 if x["streams"] == n), None)
            p2 = next((x for x in c2 if x["streams"] == n), None)
            if p1 and p2:
                d = p2["quality"] - p1["quality"]
                print(f"  {n:4d} streams: {d:+.4f}"
                      f"   ({p1['quality']:.4f} -> {p2['quality']:.4f})")


if __name__ == "__main__":
    main()
